services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: schudme
      POSTGRES_PASSWORD: schudme
      POSTGRES_DB: schudme
    ports:
      - "5432:5432"
    volumes:
      - schudme_pgdata:/var/lib/postgresql/data

volumes:
  schudme_pgdata:
