services:
  - type: web
    name: schedme-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: schedme-db
          property: connectionString
      - key: PORT
        value: 4000

databases:
  - name: schedme-db
    plan: free
    databaseName: schedme
    user: schedme
